server:
  port: 9003
livegoods:
  search:
    # 配置是否需要初始化索引，创建和设置映射。默认为false
    init:
      enabled: true
spring:
  profiles:
    # 即获取application-mongodb，application-bannerNginx的配置
    active: mongodb,bannerNginx
  application:
    name: livegoods-search
  elasticsearch:
    uris: http://192.168.126.30:9200
eureka:
  client:
    service-url:
      defaultZone: http://192.168.126.30:8761/eureka/
  instance:
    prefer-ip-address: true